=== 1g4-mirror/xkeyboard-config/rules/xkb-dev.dtd
<!--

  Description: XKB development configuration file DTD
  Authors: Sergey V. Udaltsov
           Pierre Le Marre

-->

<!ELEMENT xkbConfigRegistry (header?,modelList,layoutList,optionList)>
<!ATTLIST xkbConfigRegistry
          version CDATA "1.1">

<!ELEMENT header (#PCDATA)>

<!ELEMENT modelList (model*)>

<!ELEMENT model (configItem)>
<!ATTLIST model
          rules CDATA #IMPLIED
          priority (lowest|low|normal|high|highest) "normal"
          disabled (true|false) "false">

<!ELEMENT layoutList (layout*)>

<!ELEMENT layout (configItem,variantList?)>
<!ATTLIST layout
          rules CDATA #IMPLIED
          priority (lowest|low|normal|high|highest) "normal"
          disabled (true|false) "false">

<!ELEMENT optionList (group*)>

<!ELEMENT variantList (variant*)>

<!ELEMENT variant (configItem)>
<!ATTLIST variant
          rules CDATA #IMPLIED
          priority (lowest|low|normal|high|highest) "normal"
          disabled (true|false) "false">

<!ELEMENT group (configItem,option*)>
<!ATTLIST group
          allowMultipleSelection (true|false) "false"
          priority (lowest|low|normal|high|highest) "normal">

<!ELEMENT option (configItem)>
<!ATTLIST option
          rules CDATA #IMPLIED
          priority (lowest|low|normal|high|highest) #IMPLIED
          disabled (true|false) "false">

<!ELEMENT configItem (name,shortDescription?,description?,vendor?,(membership|member-of)?,countryList?,languageList?,hwList?,(aliases|alias)?,(rules|rule)?)>

<!ATTLIST configItem
          popularity (standard|exotic) "standard">

<!ELEMENT name (#PCDATA)>

<!ELEMENT membership (member-of+)>

<!ELEMENT member-of (#PCDATA)>
<!ATTLIST member-of
          rules CDATA #IMPLIED>

<!ELEMENT shortDescription (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT vendor (#PCDATA)>

<!ELEMENT countryList (iso3166Id+)>

<!ELEMENT iso3166Id (#PCDATA)>

<!ELEMENT languageList (iso639Id+)>

<!ELEMENT iso639Id (#PCDATA)>

<!ELEMENT hwList (hwId+)>

<!ELEMENT hwId (#PCDATA)>

<!ELEMENT aliases (alias+)>

<!ELEMENT alias EMPTY>
<!ATTLIST alias
          rules          CDATA #IMPLIED
          category       CDATA #IMPLIED
          layout         CDATA #IMPLIED
          variant        CDATA #IMPLIED
          target-variant CDATA #IMPLIED>

<!ELEMENT rules (rule+)>

<!ELEMENT rule EMPTY>
<!ATTLIST rule
          rules    CDATA #IMPLIED
          category CDATA #IMPLIED
          model    CDATA #IMPLIED
          layout   CDATA #IMPLIED
          layout-range (single | 1 | first | later | any) #IMPLIED
          variant  CDATA #IMPLIED
          option   CDATA #IMPLIED
          keycodes CDATA #IMPLIED
          compat   CDATA #IMPLIED
          geometry CDATA #IMPLIED
          symbols  CDATA #IMPLIED
          types    CDATA #IMPLIED
          priority (lowest|low|normal|high|highest) #IMPLIED>

=== 1g4-mirror/xkeyboard-config/rules/dev.legacy.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xkbConfigRegistry SYSTEM "xkb-dev.dtd">
<!--
This file is for entries that are not exposed in base*.xml files and are not
aliases, which may question their relevance.
-->
<xkbConfigRegistry>
  <modelList>
    <model>
      <configItem>
        <name>ataritt</name>
        <rules>
          <rule keycodes="ataritt(de)" rules="base"/>
          <rule layout="$nonlatin" layout-range="single" symbols="xfree68_vndr/ataritt(us)+%l%(v):2"/>
          <rule layout="*" layout-range="first" symbols="xfree68_vndr/ataritt(us)+%l[%i]%(v[%i]):%i"/>
        </rules>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>amiga</name>
        <rules>
          <rule keycodes="amiga(de)" rules="base"/>
          <rule layout="$nonlatin" layout-range="single" symbols="xfree68_vndr/amiga(usa1)+%l%(v):2"/>
          <rule layout="*" layout-range="first" symbols="xfree68_vndr/amiga(usa1)+%l[%i]%(v[%i]):%i"/>
        </rules>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>jollasbj</name>
        <member-of>$jollamodels</member-of>
        <rules>
          <rule layout="$nonlatin" layout-range="single" symbols="jolla_vndr/sbj(common)+us+%l%(v):2"/>
          <rule layout="*" layout-range="first" symbols="jolla_vndr/sbj(common)+%l[%i]%(v[%i]):%i"/>
        </rules>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>olpcm</name>
        <rules>
          <rule keycodes="evdev+olpc(olpcm)" rules="evdev"/>
          <rule layout="*" layout-range="single" compat="olpc"/>
          <rule layout="$olpclayouts" layout-range="single" symbols="olpc+%l%(m)"/>
          <rule layout="*" layout-range="single" symbols="olpc+%l%(v)"/>
        </rules>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>logicdpa</name>
        <rule symbols="+inet(logicda)" rules="base"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>logiciink</name>
        <rule symbols="+inet(logicink)" rules="base"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>ltcd</name>
        <rule symbols="+inet(logicda)" rules="base"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>sl-c3x00</name>
        <rule layout="*" layout-range="single" symbols="pc+sharp_vndr/sl-c3x00(basic)"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>ws003sh</name>
        <rule layout="*" layout-range="single" symbols="pc+sharp_vndr/ws003sh(basic)"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>ws007sh</name>
        <rule layout="*" layout-range="single" symbols="pc+sharp_vndr/ws007sh(basic)"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>ws011sh</name>
        <rule layout="*" layout-range="single" symbols="pc+sharp_vndr/ws011sh(basic)"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>ws020sh</name>
        <rule layout="*" layout-range="single" symbols="pc+sharp_vndr/ws020sh(basic)"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>intel</name>
        <member-of rules="base">$inetkbds</member-of>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>hpxe4xxx</name>
        <membership>
          <member-of rules="base">$inetkbds</member-of>
          <member-of rules="base">$inetmediakbds</member-of>
        </membership>
      </configItem>
    </model>
    <model>
      <configItem>
        <!-- FIXME: Looks bogus name -->
        <name>evdev</name>
        <member-of rules="base">$inetkbds</member-of>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>hpxe4xxx</name>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>chicony042</name>
        <member-of rules="base">$inetmediakbds</member-of>
      </configItem>
    </model>
  </modelList>
  <layoutList>
    <layout>
      <configItem>
        <name>jv</name>
        <member-of>$nonlatin</member-of>
      </configItem>
    </layout>
    <layout>
      <configItem>
        <name>---VARIANTS ONLY---</name>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>suncompat</name>
            <membership>
              <member-of>$sun_compat</member-of>
              <member-of>$sun_var</member-of>
            </membership>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>sun_type6_suncompat</name>
            <membership>
              <member-of>$sun_compat</member-of>
              <member-of>$sun_var</member-of>
            </membership>
          </configItem>
        </variant>
      </variantList>
    </layout>
  </layoutList>
  <optionList/>
</xkbConfigRegistry>

=== 1g4-mirror/xkeyboard-config/rules/dev.aliases.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xkbConfigRegistry SYSTEM "xkb-dev.dtd">
<!--
This file is for compatibility aliases.
-->
<xkbConfigRegistry>
  <modelList/>
  <layoutList/>
  <optionList>
    <group>
      <configItem>
        <name>ctrl</name>
      </configItem>
      <option>
        <!-- Delete this option alias in September 2027 -->
        <configItem>
          <name>ctrl:swapcaps_and_switch_layout</name>
          <rule symbols="+ctrl(swapcaps)+group(lctrl_toggle)" category="compatibility"/>
        </configItem>
      </option>
      <option>
        <!-- Delete this option alias in September 2027 -->
        <configItem>
          <name>ctrl:swapcaps_hyper</name>
          <rule symbols="+ctrl(hyper_capscontrol)" category="compatibility"/>
        </configItem>
      </option>
    </group>
    <group priority="low">
      <configItem>
        <name>grp</name>
      </configItem>
      <option>
        <!-- Delete this option alias in July 2027 -->
        <configItem>
          <name>grp:shift_caps_switch</name>
          <rule symbols="+group(caps_select)" category="compatibility"/>
        </configItem>
      </option>
      <option>
        <!-- Delete this option alias in July 2027 -->
        <configItem>
          <name>grp:win_menu_switch</name>
          <rule symbols="+group(win_menu_select)" category="compatibility"/>
        </configItem>
      </option>
      <option>
        <!-- Delete this option alias in July 2027 -->
        <configItem>
          <name>grp:lctrl_rctrl_switch</name>
          <rule symbols="+group(ctrl_select)" category="compatibility"/>
        </configItem>
      </option>
    </group>
  </optionList>
</xkbConfigRegistry>

=== 1g4-mirror/xkeyboard-config/rules/dev.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xkbConfigRegistry SYSTEM "xkb-dev.dtd">
<!--
This file is for special entries (wildcards, groups) that cannot appear
in base*.xml but are required for rules generation.
-->
<xkbConfigRegistry>
  <modelList>
    <model>
      <configItem>
        <name>*</name>
        <rules>
          <rule keycodes="evdev" rules="evdev"/>
          <rule keycodes="xfree86" rules="base"/>
          <rule geometry="pc(pc104)"/>
          <rule layout="*" layout-range="first" compat="complete"/>
          <rule symbols="+inet(evdev)" rules="evdev"/>
          <rule layout="$nonlatin" layout-range="single" symbols="pc+us+%l%(v):2"/>
          <rule layout="$sun_custom" layout-range="single" variant="$sun_var" symbols="pc+sun_vndr/%l%(v)"/>
          <rule layout="*" layout-range="first" symbols="pc+%l[%i]%(v[%i]):%i"/>
          <rule layout="*" layout-range="later" symbols="+%l[%i]%(v[%i]):%i"/>
          <rule types="complete"/>
        </rules>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>empty</name>
        <rules>
          <rule keycodes="empty" rules="base"/>
          <rule layout="*" layout-range="single" symbols="empty(basic)" priority="highest"/>
        </rules>
      </configItem>
    </model>
    <!-- Groups -->
    <model>
      <configItem>
        <name>$pcmodels</name>
        <description>PC models</description>
        <rule geometry="pc(%m)"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>$jollamodels</name>
        <description>Jolla devices and keyboards</description>
        <rule keycodes="evdev+jolla(jolla)" rules="evdev"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>$sun</name>
        <rules>
          <rule keycodes="sun(type6_usb)" rules="base"/>
          <rule symbols="+sun_vndr/solaris(defaults)" rules="base"/>
          <rule layout="$sun_custom" layout-range="first" symbols="pc+sun_vndr/%l[%i]%(v[%i]):%i"/>
          <rule layout="$sun_custom" layout-range="later" symbols="+sun_vndr/%l[%i]%(v[%i]):%i"/>
        </rules>
      </configItem>
    </model>
    <model rules="base">
      <configItem>
        <name>$sun_jp</name>
        <rule keycodes="sun(type6_jp_usb)" rules="base"/>
      </configItem>
    </model>
    <model rules="base">
      <configItem>
        <name>$inetkbds</name>
        <rule symbols="+inet(%m)" rules="base"/>
      </configItem>
    </model>
    <model rules="base">
      <configItem>
        <name>$inetmediakbds</name>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>$msmodels</name>
        <description>Microsoft models (using MS geometry)</description>
        <rule geometry="microsoft(natural)"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>$tmgeometries</name>
        <description>TypeMatrix geometries</description>
        <rule geometry="typematrix(%m)"/>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>$thinkpads</name>
      </configItem>
    </model>
    <model>
      <configItem>
        <name>$applealu</name>
        <rules>
          <rule keycodes="macintosh(alukbd)" rules="base"/>
          <rule geometry="macintosh(%m)"/>
          <rule symbols="+inet(apple)" rules="base"/>
          <rule layout="$macvendorlayouts" layout-range="first" symbols="macintosh_vndr/apple(alukbd)+macintosh_vndr/%l[%i]%(v[%i]):%i"/>
          <rule layout="*" layout-range="first" symbols="macintosh_vndr/apple(alukbd)+%l[%i]%(v[%i]):%i"/>
          <rule types="complete+numpad(mac)"/>
        </rules>
      </configItem>
    </model>
  </modelList>
  <layoutList>
    <layout>
      <configItem>
        <name>*</name>
        <rule layout-range="first" keycodes="+aliases(qwerty)"/>
      </configItem>
    </layout>
    <layout>
      <configItem>
        <name>empty</name>
        <rule model="*" layout-range="single" symbols="empty(basic)" priority="highest"/>
      </configItem>
    </layout>
    <!-- Groups -->
    <layout disabled="true">
      <configItem>
        <name>$nonlatin</name>
        <description>
          If you want non-latin layouts to implicitly include the en_US layout,
          then uncomment the following lines:
        </description>
      </configItem>
    </layout>
    <layout>
      <configItem>
        <name>$azerty</name>
        <description>
          The countries that predominantly have AZERTY layouts:
        </description>
        <rule layout-range="first" keycodes="+aliases(azerty)"/>
      </configItem>
    </layout>
    <layout>
      <configItem>
        <name>$qwertz</name>
        <description>
          The countries that predominantly have QWERTZ layouts:
        </description>
        <rule layout-range="first" keycodes="+aliases(qwertz)"/>
      </configItem>
    </layout>
    <layout>
      <configItem>
        <name>$macvendorlayouts</name>
      </configItem>
    </layout>
    <layout>
      <configItem>
        <name>$olpclayouts</name>
        <description>Country files that provide specializations for the OLPC:</description>
      </configItem>
    </layout>
    <layout>
      <configItem>
        <name>$sun_custom</name>
        <description>Sun Type_6_7 keyboards with custom layouts</description>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>$sun_var</name>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>$sun_compat</name>
          </configItem>
        </variant>
      </variantList>
    </layout>
  </layoutList>
  <optionList/>
</xkbConfigRegistry>
